apiVersion: skaffold/v1beta5
kind: Config
build:
  artifacts:
    -
      image: sampleservice
      context: src
  local:
    push: false
    useDockerCLI: true
    useBuildkit: false
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - 'kubernetes-manifests/**.yaml'
