apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sampleservice
spec:
  template:
    metadata:
      labels:
        app: sampleservice
    spec:
      containers:
      - name: server
        image: sampleservice
        ports:
        - containerPort: 1905
---
apiVersion: v1
kind: Service
metadata:
  name: sampleservice
spec:
  type: NodePort
  selector:
    app: sampleservice
  ports:
  - name: http
    port: 1905
    nodePort: 31905